# This is Assignment 11 - Michael Navarro

In [1]:
# Imports
import numpy as np
import pandas as pd

## Requirement 03

The commonalities between NumPy arrays and Pandas series are about the same as NumPy arrays and Python lists. That is, they both store data in list like format (with their respective limitations) to be used with each of their respective methods. You can do similar operations in both a NumPy array and a Pandas series however, this is where we can start to see a difference.

NumPy Arrays are favored when having to do calculations, especially if those operations are repeated numerous times. NumPy arrays also tend to take less space then Pandas Series. Pandas Series however, are better suited for data modeling as they can use labels to organize their data and by using an index, multiple data series can become a data frame allowing for greater modeling methods.

## Requirement 04

In [2]:
# Create a Pandas series named bill_names with American currency bill
# denominations as indices (keys) and President last names as values. For
# example: 1 – Washington, 2 – Jefferson, etc

bill_names = pd.Series(["Washington", "Jefferson", "Lincoln", "Hamilton", "Jackson", "Grant", "Franklin"],
index=[1, 2, 5, 10, 20, 50, 100])

bill_names

1      Washington
2       Jefferson
5         Lincoln
10       Hamilton
20        Jackson
50          Grant
100      Franklin
dtype: object

## Requirement 05

In [3]:
# Create a Pandas series-as-dictionary beverages_dict. Make the indices
# beverage names and comments about the beverage as values. For example:
# ‘Aquafina’: ‘This is my favorite bottled water!’. Demonstrate accessing:
# • individual values via the keys
# • multiple values via slicing

beverages_dict = pd.Series({
    'Fanta': "Don't cha?",
    'Dr. Pepper': "Thank you Dublin!",
    'Coke': "Delicious",
    'Pepsi': "Not coke :(",
})

print(f'Fanta: {beverages_dict["Fanta"]}')
print(f'Dr. Pepper: {beverages_dict["Dr. Pepper"]}')
print(f'Coke: {beverages_dict["Coke"]}')
print(f'Pepsi: {beverages_dict["Pepsi"]}')

beverages_dict['Coke':'Pepsi']

Fanta: Don't cha?
Dr. Pepper: Thank you Dublin!
Coke: Delicious
Pepsi: Not coke :(


Coke       Delicious
Pepsi    Not coke :(
dtype: object

## Requirement 06

In [4]:
# Obtain the real city proper population data for the following cities:
# Chongquing, Shanghai, Tokyo, Moscow, Mexico City, London, & New York.
# Create a series-as-dictionary named population based on this information.

population = pd.Series({
    'Chongquing'    : 16382000,
    'Shanghai'      : 27796000,
    'Tokyo'         : 125920841,
    'Moscow'        : 12593252,
    'Mexico City'   : 21918936,
    'London'        : 9425622,
    'New York'      : 8230290,
})

population


Chongquing      16382000
Shanghai        27796000
Tokyo          125920841
Moscow          12593252
Mexico City     21918936
London           9425622
New York         8230290
dtype: int64

## Requirement 07

In [5]:
# Create a Pandas series-as-dictionary named city_country with the cities in
# population and the countries for each city

city_country = pd.Series({
    'Chongquing'    : 'China',
    'Shanghai'      : 'China',
    'Tokyo'         : 'Japan',
    'Moscow'        : 'Russia',
    'Mexico City'   : 'Mexico',
    'London'        : 'UK',
    'New York'      : 'USA',
})

city_country

Chongquing      China
Shanghai        China
Tokyo           Japan
Moscow         Russia
Mexico City    Mexico
London             UK
New York          USA
dtype: object

## Requirement 08

In [6]:
# Create a Pandas dataframe object named city_dataframe from a dictionary
# of series objects using population and city_country. Show:
# • the .index property
# • the .columns property
# • the .keys() method

city_dataframe = pd.DataFrame({
    'population':population,
    'city_country': city_country,
})

print(f'{city_dataframe}\n')
print(f'Index Access:\n{city_dataframe.index}\n')
print(f'Column Access:\n{city_dataframe.columns}\n')
print(f'Keys() Method:\n{city_dataframe.keys()}')

             population city_country
Chongquing     16382000        China
Shanghai       27796000        China
Tokyo         125920841        Japan
Moscow         12593252       Russia
Mexico City    21918936       Mexico
London          9425622           UK
New York        8230290          USA

Index Access:
Index(['Chongquing', 'Shanghai', 'Tokyo', 'Moscow', 'Mexico City', 'London',
       'New York'],
      dtype='object')

Column Access:
Index(['population', 'city_country'], dtype='object')

Keys() Method:
Index(['population', 'city_country'], dtype='object')


## Requirement 09

In [7]:
# Create a Pandas series object named my_pd_series from a collection of
# string keys and collection of numeric values of your choosing. Demonstrate:
# • modifying a value based on key
# • slicing by explicit index
# • slicing by implicit integer index
# • masking
# • fancy indexing
# • loc[]
# • iloc[]

my_pd_series = pd.Series([1980, 1990, 1996, 2001, 2006, 2012, 2017], 
                    index=['Nintendo Entertainment System', 'Super Nintendo Entertainment System', 'Nintendo 64', 'Nintendo GameCube', 'Wii', 'Wii U', 'Nintendo Switch'])

# my_pd_series = ({
#     'Nintendo Entertainment System' : 1980,
#     'Super Nintendo Entertainment System' : 1990,
#     'Nintendo 64' : 1996,
#     'Nintendo GameCube' : 2001,
#     'Wii' : 2006,
#     'Wii U' : 2012,
#     'Nintendo Switch' : 2017,
# })

print(f'Nintendo Entertainment System Release Date: {my_pd_series["Nintendo Entertainment System"]}')
my_pd_series["Nintendo Entertainment System"] = 1983
print(f'Correction: {my_pd_series["Nintendo Entertainment System"]}')

print(f'\nSlicing by explicit index:\n{my_pd_series["Wii" : "Nintendo Switch"]}')
print(f'\nSlicing by implicit integer index:\n{my_pd_series[0:3]}')
print(f'\nMasking:\n{my_pd_series[(my_pd_series >= 1990) & (my_pd_series <= 2000)]}')
print(f'\nFancy Indexing:\n{my_pd_series[["Nintendo Entertainment System", "Nintendo Switch"]]}')

print(f'\nLoc["Nintendo Entertainment System"]:\n{my_pd_series.loc["Nintendo Entertainment System"]}')
print(f'\nIloc[0]:\n{my_pd_series.iloc[0]}')

Nintendo Entertainment System Release Date: 1980
Correction: 1983

Slicing by explicit index:
Wii                2006
Wii U              2012
Nintendo Switch    2017
dtype: int64

Slicing by implicit integer index:
Nintendo Entertainment System          1983
Super Nintendo Entertainment System    1990
Nintendo 64                            1996
dtype: int64

Masking:
Super Nintendo Entertainment System    1990
Nintendo 64                            1996
dtype: int64

Fancy Indexing:
Nintendo Entertainment System    1983
Nintendo Switch                  2017
dtype: int64

Loc["Nintendo Entertainment System"]:
1983

Iloc[0]:
1983


## Requirement 10

In [8]:
# Using city_dataframe, demonstrate:
# • access column via dictionary-style indexing of the column name
# • access column via column names that are strings
# • add a new column to the city_dataframe named altitude.

print(f'Dictionary-style indexing of the column name "Population":\n{city_dataframe["population"]}')
print(f'\nAccess column via column names that are strings "city_country":\n{city_dataframe.city_country}')

city_dataframe['Population 2022'] = city_dataframe['population'] * 1.05
print()
print(city_dataframe)

Dictionary-style indexing of the column name "Population":
Chongquing      16382000
Shanghai        27796000
Tokyo          125920841
Moscow          12593252
Mexico City     21918936
London           9425622
New York         8230290
Name: population, dtype: int64

Access column via column names that are strings "city_country":
Chongquing      China
Shanghai        China
Tokyo           Japan
Moscow         Russia
Mexico City    Mexico
London             UK
New York          USA
Name: city_country, dtype: object

             population city_country  Population 2022
Chongquing     16382000        China     1.720110e+07
Shanghai       27796000        China     2.918580e+07
Tokyo         125920841        Japan     1.322169e+08
Moscow         12593252       Russia     1.322291e+07
Mexico City    21918936       Mexico     2.301488e+07
London          9425622           UK     9.896903e+06
New York        8230290          USA     8.641804e+06


## Requirement 11

In [9]:
# Create two Pandas series that when added using ‘+’ produce some NaN
# entries. Use the .add() method and a fill_value to replace the NaN entries

X = pd.Series([4, 8, 12], index=[0, 0, 4])
Y = pd.Series([2, 6, 10], index=[2, 4, 6])

print('Unfilled')
print(X + Y)
print('\nFilled')
print(f'{X.add(Y, fill_value=0)}')

Unfilled
0     NaN
0     NaN
2     NaN
4    18.0
6     NaN
dtype: float64

Filled
0     4.0
0     8.0
2     2.0
4    18.0
6    10.0
dtype: float64


## Requirement 12

In [10]:
# Create two Pandas dataframes that when added using ‘+’ produce some
# NaN entries. Use the .add() method and a fill_value of the mean of one of
# the dataframes to replace the NaN entries

rng = np.random.RandomState(99)

X = pd.DataFrame(rng.randint(0, 20, (2, 2)),
    columns=list('AB'))
Y = pd.DataFrame(rng.randint(0, 10, (3, 3)),
    columns=list('BAC'))

print('Unfilled')
print(X + Y)
print('\nFilled')
fill = X.stack().mean()
print(f'{X.add(Y, fill_value=fill)}')

Unfilled
      A     B   C
0   3.0  11.0 NaN
1  12.0  14.0 NaN
2   NaN   NaN NaN

Filled
       A      B      C
0   3.00  11.00   9.25
1  12.00  14.00   6.25
2   8.25  12.25  12.25


## Requirement 13

In [11]:
# Create a two-dimensional NumPy array using:
# A = rng.randint(5, 10, size=(4, 4))
# Demonstrate: subtracting row 0 of A from A

A = rng.randint(5, 10, size=(4, 4))

print('Original')
print(A)
print('\nSubtracting row 0 of A from A')
print(A - A[0])

Original
[[6 6 5 8]
 [8 9 7 5]
 [9 5 5 9]
 [6 8 7 8]]

Subtracting row 0 of A from A
[[ 0  0  0  0]
 [ 2  3  2 -3]
 [ 3 -1  0  1]
 [ 0  2  2  0]]


## Requirement 14

In [12]:
# Create a Pandas dataframe using:
# df = pd.DataFrame(A, columns=list('QRST'))
# Demonstrate: subtracting row 1 of df from df using df.iloc[1]

df = pd.DataFrame(A, columns=list('QRST'))

print('Original')
print(df)
print('\nSubtracting row 1 of df from df using df.iloc[1]')
print(df - df.iloc[0])

Original
   Q  R  S  T
0  6  6  5  8
1  8  9  7  5
2  9  5  5  9
3  6  8  7  8

Subtracting row 1 of df from df using df.iloc[1]
   Q  R  S  T
0  0  0  0  0
1  2  3  2 -3
2  3 -1  0  1
3  0  2  2  0


## Requirement 15

The two different sentinel values that Pandas uses are NaN (Not a number) and None. The key diference is how the two values can be used with arithmetic in regards to NumPy. None signifies an absence of data. NaN while not a number can still be manipulated like one under the hood. For Pandas, in general, Pandas can deal with both in just about the same way meaning that they can generally act the same way, for Pandas. Additionally, Pandas has some unqiue ways of manipulating NaN and None.

## Requirement 16

In [13]:
# Demonstrate the %timeit difference between operations using Python
# objects and Python integers

for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E5, dtype=dtype).sum()
    print()
# end for

dtype = object
3.98 ms ± 44.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

dtype = int
73.3 µs ± 477 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)



## Requirement 17

In [14]:
# Create a Pandas series containing null data. Use .isnull() to identify the
# entries that are null.

null_data = pd.Series([np.nan, None, 12, 23, 34])

print('Values that are NULL')
null_data.isnull()

Values that are NULL


0     True
1     True
2    False
3    False
4    False
dtype: bool

## Requirement 18

In [15]:
# Create a Pandas dataframe containing null values. Demonstrate
# • drop all rows containing a null value
# • drop all columns containing a null value
# • drop only rows that contain all null values
# • drop only columns that contain all null values
# • replacing null with 0
# • forward fill
# • backward fill

null_df = pd.DataFrame([[None,   0,      np.nan],
                        [3,      10,     5],
                        [np.nan, 4,      None]])

print(f'Original:\n{null_df}')
print(f'\nDrop all rows containing a null value:\n{null_df.dropna()}')
print(f'\nDrop all columns containing a null value:\n{null_df.dropna(axis="columns")}')

null_df = pd.DataFrame([[None,   np.nan, np.nan],
                        [3,      10,     5],
                        [np.nan, 4,      None]])
print('\n========== Dataframe Re-init ==========')
print(f'Original:\n{null_df}')                       
print(f'\nDrop only rows that contain all null values:\n{null_df.dropna(axis="rows", how="all")}')

null_df = pd.DataFrame([[1,   np.nan, np.nan],
                        [3,      10,     None],
                        [np.nan, 4,      None]])
print('\n========== Dataframe Re-init ==========')
print(f'Original:\n{null_df}')   
print(f'\nDrop only columns that contain all null values:\n{null_df.dropna(axis="columns", how="all")}')

print(f'\nReplacing null with 0:\n{null_df.fillna(0)}')
print(f'\nForward fill:\n{null_df.fillna(method="ffill")}')
print(f'\nBackward fill:\n{null_df.fillna(method="bfill")}')


Original:
     0   1    2
0  NaN   0  NaN
1  3.0  10  5.0
2  NaN   4  NaN

Drop all rows containing a null value:
     0   1    2
1  3.0  10  5.0

Drop all columns containing a null value:
    1
0   0
1  10
2   4

========== Dataframe Re-init ==========
Original:
     0     1    2
0  NaN   NaN  NaN
1  3.0  10.0  5.0
2  NaN   4.0  NaN

Drop only rows that contain all null values:
     0     1    2
1  3.0  10.0  5.0
2  NaN   4.0  NaN

========== Dataframe Re-init ==========
Original:
     0     1   2
0  1.0   NaN NaN
1  3.0  10.0 NaN
2  NaN   4.0 NaN

Drop only columns that contain all null values:
     0     1
0  1.0   NaN
1  3.0  10.0
2  NaN   4.0

Replacing null with 0:
     0     1    2
0  1.0   0.0  0.0
1  3.0  10.0  0.0
2  0.0   4.0  0.0

Forward fill:
     0     1   2
0  1.0   NaN NaN
1  3.0  10.0 NaN
2  3.0   4.0 NaN

Backward fill:
     0     1   2
0  1.0  10.0 NaN
1  3.0  10.0 NaN
2  NaN   4.0 NaN


## Requirement 19

In [16]:
# Demonstrate Pandas MultiIndex techniques (can use book examples):
# • .from_tuples()
# • .reindex()
# • .unstack()
# • .stack()
# • indexing and slicing



index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
               
pop = pd.Series(populations, index=index)
index = pd.MultiIndex.from_tuples(index)

print('========= FROM_TUPLES() ==========')
print('Note: For some reason my output would not output the same as the book.')
print(index)

print('\n========= REINDEX ==========')
pop = pop.reindex(index)
print(pop)

print('\n========= UNSTACK ==========')
pop_df = pop.unstack()
print(pop_df)

print('\n========= STACK ==========')
print(pop_df.stack())

print('\n========= INDEXING ==========')
print('California')
print(pop['California'])

print('\n========= SLICING ==========')
print(pop[:, 2010])

========= FROM_TUPLES() ==========
Note: For some reason my output would not output the same as the book.
MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

========= REINDEX ==========
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

========= UNSTACK ==========
                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

========= STACK ==========
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

========= INDEXING ==========
California
2000    33871648
2010    37253956
dtype: int64



## Requirement 20

In [17]:
# Demonstrate concatenating two Pandas series. One series contains
# automobile data. The other series contains motorcycle data

cars = pd.Series(['Honda Civic', 'Mazda Mazda3', 'Hyundai Elantra Hybrid'], index=[1, 2, 3])
bikes = pd.Series(['Royal Enfield Meteor 350', 'Triumph Trident 660', 'Yamaha Tenere 700'], index=[4, 5, 6])
pd.concat([cars, bikes])

1                 Honda Civic
2                Mazda Mazda3
3      Hyundai Elantra Hybrid
4    Royal Enfield Meteor 350
5         Triumph Trident 660
6           Yamaha Tenere 700
dtype: object

## Requirement 21

In [18]:
# Demonstrate concatenating two Pandas dataframe using the .append()
# method

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)
# end class display()

def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)
# end make_df()

df1 = make_df('XY', [1, 5])
df2 = make_df('XY', [3, 8])

display('df1', 'df2', 'df1.append(df2)')

df1
    X   Y
1  X1  Y1
5  X5  Y5

df2
    X   Y
3  X3  Y3
8  X8  Y8

df1.append(df2)
    X   Y
1  X1  Y1
5  X5  Y5
3  X3  Y3
8  X8  Y8

## Requirement 22

In [19]:
# Using Pandas dataframes, demonstrate the following joins:
# • one-to-one
# • many-to-one
# • many-to-many

df1 = pd.DataFrame({'game': ['Radiant Historia', 'Xenogears', 'Chrono Cross', 'Persona 5'],
                    'console': ['3DS', 'PC', 'PC', 'Playstation 4']})
df2 = pd.DataFrame({'game': ['Chrono Cross', 'Radiant Historia', 'Xenogears', 'Persona 5'],
                    'release_date': [1999, 2010, 1998, 2016]})

df3 = pd.merge(df1, df2)
print('One-to-one')
df3


One-to-one


game        console  release_date
0  Radiant Historia            3DS          2010
1         Xenogears             PC          1998
2      Chrono Cross             PC          1999
3         Persona 5  Playstation 4          2016

In [20]:
df4 = pd.DataFrame({'console': ['3DS', 'PC', 'Playstation 4'],
                    'manufacturer': ['Nintendo', 'Windows', 'Sony']})
print('Many-to-one')
pd.merge(df3, df4)

Many-to-one


game        console  release_date manufacturer
0  Radiant Historia            3DS          2010     Nintendo
1         Xenogears             PC          1998      Windows
2      Chrono Cross             PC          1999      Windows
3         Persona 5  Playstation 4          2016         Sony

In [22]:
print('Many-to-many')
df5 = pd.DataFrame({'console': ['3DS', '3DS',
                              'PC', 'PC', 'Playstation 4', 'Playstation 4'],
                    'models': ['Lite', 'XL', 'Stock', 'Custom',
                               'Slim', 'Pro']})
pd.merge(df1, df5)

Many-to-many


game        console  models
0  Radiant Historia            3DS    Lite
1  Radiant Historia            3DS      XL
2         Xenogears             PC   Stock
3         Xenogears             PC  Custom
4      Chrono Cross             PC   Stock
5      Chrono Cross             PC  Custom
6         Persona 5  Playstation 4    Slim
7         Persona 5  Playstation 4     Pro

## Requirement 23

In [25]:
# Using Pandas dataframes, demonstrate merge with the following
# keywords:
# • on
# • left_on and right_on
# • left_index and right_index

display("pd.merge(df1, df2, on='game')")

pd.merge(df1, df2, on='game')
               game        console  release_date
0  Radiant Historia            3DS          2010
1         Xenogears             PC          1998
2      Chrono Cross             PC          1999
3         Persona 5  Playstation 4          2016

In [26]:
df3 = pd.DataFrame({'video_game': ['Radiant Historia', 'Xenogears', 'Chrono Cross', 'Persona 5'],
                    'sales': [32800, 890000, 1500000, 1800000]})

display('pd.merge(df1, df3, left_on="game", right_on="video_game")')

pd.merge(df1, df3, left_on="game", right_on="video_game")
               game        console        video_game    sales
0  Radiant Historia            3DS  Radiant Historia    32800
1         Xenogears             PC         Xenogears   890000
2      Chrono Cross             PC      Chrono Cross  1500000
3         Persona 5  Playstation 4         Persona 5  1800000

In [29]:
df1a = df1.set_index('game')
df2a = df2.set_index('game')
display("pd.merge(df1a, df2a, left_index=True, right_index=True)")

pd.merge(df1a, df2a, left_index=True, right_index=True)
                        console  release_date
game                                         
Radiant Historia            3DS          2010
Xenogears                    PC          1998
Chrono Cross                 PC          1999
Persona 5         Playstation 4          2016

## Requirement 24

I had an absolute blast and learned a lot with this assignment. I had a slight display issue in one of the requirements, but I'm not sure if its because of my environment setup. The proceeding requirement had the desired output so the requirement with a display issue did at least function correctly. I really enjoyed that I was able to come up with my own series and dataframes to see if I could recreate them in a different way, but still be able to accomplish the desired functionality. All in all, my favorite assignment, hands down.