# Certification

I certify that this project is my own work and is not the work of others. I agree not to share my solution with others. - Michael Navarro.

# Solving a system of equations

The objective of this notebook is to demonstrate how to solve a system of equations using SciPy such as the one below:

$
\begin{aligned}
 16v +17w +12x  +66y +45z &= 156 \\
 29v -18w -15x  +73y +70z &= 139 \\
-14v +46w -27x  +58y +91z &= 154 \\
 33v +37w +24x -123y +54z &=  25 \\
 20v -27w +18x  +19y -56z &= -26
\end{aligned}
$

## Imports

First we must import the libraries we will use. The ones needed are SciPy and Numpy

In [8]:
# Imports
import numpy as np
from scipy import linalg

## Introduction

In order to use SciPy to solve the system of equations we have to convert the equations ito Numpy matrices. This is done by taking the coefficients of the left hand side and storing them into one multidimensional array and storing the respective solutions to the equations into another multidimensional array.

Below is an example of how the matrix is created when solving by hand. Each row will be a separate array in the Numpy array.

$
\begin{equation*}
\begin{vmatrix}
\mathbf{v} \\
\mathbf{w} \\
\mathbf{x} \\
\mathbf{y} \\
\mathbf{z}
\end{vmatrix} =
\begin{vmatrix}
\mathbf{16}  & \mathbf{17}  & \mathbf{12}  & \mathbf{66}   & \mathbf{45} \\
\mathbf{29}  & \mathbf{-18} & \mathbf{-15} & \mathbf{73}   & \mathbf{70} \\
\mathbf{-14} & \mathbf{46}  & \mathbf{-27} & \mathbf{58}   & \mathbf{91} \\
\mathbf{33}  & \mathbf{37}  & \mathbf{24}  & \mathbf{-123} & \mathbf{54} \\
\mathbf{20}  & \mathbf{-27} & \mathbf{18}  & \mathbf{19}   & \mathbf{-56} \\
\end{vmatrix}
\begin{vmatrix}
\mathbf{156} \\
\mathbf{139} \\
\mathbf{154} \\
\mathbf{25} \\
\mathbf{-26}
\end{vmatrix}
\end{equation*}
$

## Step 01: Create Numpy Arrays

The first step is to take the coefficients for each row and insert them into a Numpy array as their own array.

In [9]:
A = np.array([
    [16, 17, 12, 66, 45],
    [29,-18,-15, 73, 70],
    [-14,46,-27, 58, 91],
    [33, 37, 24,-123,54],
    [20,-27, 18, 19,-56]
])

print('Array of arrays representing the left hand side of the equations.')
print(A)

Array of arrays representing the left hand side of the equations.
[[  16   17   12   66   45]
 [  29  -18  -15   73   70]
 [ -14   46  -27   58   91]
 [  33   37   24 -123   54]
 [  20  -27   18   19  -56]]


Now we will do the same for the solutions to the equations. It is important that they follow the same ordering and each value is stored in its own arrary as well.

In [10]:
b = np.array([
    [156],
    [139],
    [154],
    [25],
    [-26]
])

print('Array of arrays representing the solution for each equation.')
print(b)

Array of arrays representing the solution for each equation.
[[156]
 [139]
 [154]
 [ 25]
 [-26]]


## Step 02: Solve Using SciPy

In order to solve using SciPy we will be using the linalg() method imported. We will supply the array we created for the coefficients of the equations (A) as the first parameter and the array of solutions (b) as the second parameter.

The result will be stored in a new variable called vwxyz after the variables we are solving for. Really, you can call it whatever you would like.

In [11]:
vwxyz = np.linalg.solve(A, b)

print('The solution for the system of equations is:')
print(vwxyz)

The solution for the system of equations is:
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


## Step 03: Check Answer

The final step is to double check our answer. Luckily, there is an easy way to do this by using the dot() method. For this method the only parameter we need to pass in is the variable we saved the result of the linalg() method we called earlier. The dot() method computes the dot product using the linalg() result and the original array 'A'. We can then compare the result of the dot() method wth array 'b' to see if they are the same.

In [12]:
idx = 0

# Iterate throught the array from the result of dot() method.
# Compare each entry with those of array 'b'.
for arr in A.dot(vwxyz):
    print(f'{arr[0]: <4.0f} =  {b[idx][0]}')
    idx += 1 
# end for

156  =  156
139  =  139
154  =  154
25   =  25
-26  =  -26


Using the dot() method we can see that the solution returned from the linalg() method is indeed correct since it matches the array 'b' which stored the solutions to the orignal equations. Therefore, our solution is:

$
\begin{aligned}
v &= 1 \\
w &= 1 \\
x &= 1 \\
y &= 1 \\
z &= 1 
\end{aligned}
$